baseURL = '/'
languageCode = 'en-us'
title = 'Benji Peng, Ph.D.'
theme = 'lynx'

defaultContentLanguage = "en"

copyright = "_RenoCrypt_ &copy;"

enableEmoji = true
disableKinds = ["taxonomy", "term"]
googleAnalytics = "G-6L7V5YG0QJ"


[params.author]
name = "Benji Peng, Ph.D."
headline = "Biophysicist / Co-founding... / A.K.A Dr. Honeycutt"
image = "benji.webp"                                             # path relative to static directory

links = [
  { github = "https://github.com/benjipeng" },
  { linkedin = { href = "https://linkedin.com/in/benjiph" } },
  # { linkin = { href = "https://linkedin.com/in/benjiph", text = "LinkedIn" } },
  { x = { href = "https://twitter.com/benjipeng", text = "Formerly Twitter" } },
  { instagram = "https://instagram.com/ben_flyer" },
  # { email = "mailto:hello@your_domain.com" },
  { discord = "https://discordapp.com/users/787673267657244682" },
  # { apple = "https://www.apple.com" },
  # { codepen = "https://codepen.io/username" },
  # { dev = "https://dev.to/username" },
  # { discord = "https://discord.gg/invitecode" },
  # { dribbble = "https://dribbble.com/username" },
  # { facebook = "https://facebook.com/username" },
  # { flickr = "https://www.flickr.com/photos/username/" },
  # { foursquare = "https://foursquare.com/username" },
  # { gitlab = "https://gitlab.com/benjipeng" },
  # { google = "https://www.google.com/" },
  # { keybase = "https://keybase.io/username" },
  # { kickstarter = "https://www.kickstarter.com/profile/username" },
  # { lastfm = "https://lastfm.com/user/username" },
  # { mastodon = "https://mastodon.instance/@username" },
  # { medium = "https://medium.com/username" },
  # { microsoft = "https://www.microsoft.com/" },
  # { patreon = "https://www.patreon.com/username" },
  # { pinterest = "https://pinterest.com/username" },
  # { reddit = "https://reddit.com/user/username" },
  # { slack = "https://workspace.url/team/userid" },
  # { snapchat = "https://snapchat.com/add/username" },
  # { soundcloud = "https://soundcloud.com/username" },
  # { stack-exchange = "https://stackexchange.com/users/userid/username" },
  # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  # { steam = "https://steamcommunity.com/profiles/userid" },
  { telegram = "https://t.me/itglue" },
  # { tiktok = "https://tiktok.com/@username" },
  # { tumblr = "https://username.tumblr.com" },
  # { twitch = "https://twitch.tv/username" },
  # { whatsapp = "https://wa.me/phone-number" },
  # { youtube = "https://youtube.com/username" },
  { orcid = { href = "https://benji-scientist.renocrypt.com/", text = "More About My Research" } },
  { pen-nib = { href = "https://benji-design.renocrypt.com", text = "Designed by Benji" } },
  { web = { href = "https://www.renocrypt.com", text = "Blog On Science / ML" } },
]

[module]
[module.hugoVersion]
extended = false
# min = "0.86.1"
