baseURL = 'https://benji.renocrypt.com'
languageCode = 'en-us'
title = 'Benji Peng, Ph.D.'
theme = 'lynx'

defaultContentLanguage = "en"

copyright = "_RenoCrypt_ &copy;2023 :ice:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
name = "Benji Peng, Ph.D."
headline = "Co-Founding Software Engineer / Product Development Specialist"
image = "benji.jpg"                                                         # path relative to static directory

links = [
  { email = "mailto:hello@your_domain.com" },
  { link = { href = "https://benji.appcubic.com/", text = "Website" } },
  { research = { href = "https://research.appcubic.com/", text = "Research" } },
  # { apple = "https://www.apple.com" },
  # { codepen = "https://codepen.io/username" },
  # { dev = "https://dev.to/username" },
  # { discord = "https://discord.gg/invitecode" },
  # { dribbble = "https://dribbble.com/username" },
  # { facebook = "https://facebook.com/username" },
  # { flickr = "https://www.flickr.com/photos/username/" },
  # { foursquare = "https://foursquare.com/username" },
  { github = "https://github.com/benjipeng" },
  # { gitlab = "https://gitlab.com/benjipeng" },
  # { google = "https://www.google.com/" },
  # { instagram = "https://instagram.com/username" },
  # { keybase = "https://keybase.io/username" },
  # { kickstarter = "https://www.kickstarter.com/profile/username" },
  # { lastfm = "https://lastfm.com/user/username" },
  { linkedin = "https://linkedin.com/in/benjiph" },
  # { mastodon = "https://mastodon.instance/@username" },
  # { medium = "https://medium.com/username" },
  # { microsoft = "https://www.microsoft.com/" },
  # { patreon = "https://www.patreon.com/username" },
  # { pinterest = "https://pinterest.com/username" },
  # { reddit = "https://reddit.com/user/username" },
  # { slack = "https://workspace.url/team/userid" },
  # { snapchat = "https://snapchat.com/add/username" },
  # { soundcloud = "https://soundcloud.com/username" },
  # { stack-exchange = "https://stackexchange.com/users/userid/username" },
  # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  # { steam = "https://steamcommunity.com/profiles/userid" },
  { telegram = "https://t.me/itglue" },
  # { tiktok = "https://tiktok.com/@username" },
  # { tumblr = "https://username.tumblr.com" },
  # { twitch = "https://twitch.tv/username" },
  # { twitter = "https://twitter.com/username" },
  # { whatsapp = "https://wa.me/phone-number" },
  # { youtube = "https://youtube.com/username" },
]

[module]
[module.hugoVersion]
extended = false
# min = "0.86.1"
